CREATE TABLE IF NOT EXISTS  `{project_id}.pss_dataset.calendar` (
    dim_date_id       INT64         OPTIONS(description="date_dim_id"),
    dim_date       DATE         OPTIONS(description="date_actual"),
    epoch       INT64         OPTIONS(description="EPOCH UNIX timestamp"),
    day_of_week       INT64         OPTIONS(description="day of the week"),
    day_of_month       INT64         OPTIONS(description="day of the month"),
    day_of_year       INT64         OPTIONS(description="day of the year"),
    week_of_year       INT64         OPTIONS(description="week of the year"),
    month_of_year       INT64         OPTIONS(description="month actual number"),
    month_name       STRING         OPTIONS(description="name of the month "),
    month_name_abbreviated       STRING         OPTIONS(description="abbreviated name of the month"),
    day_name       STRING         OPTIONS(description="name of the day"),
    day_name_abbreviated       STRING         OPTIONS(description="day_abbreviated"),
    quarter_of_year       INT64         OPTIONS(description="quarter actual number"),
    quarter_name       STRING         OPTIONS(description="quarter name"),
    dim_year       INT64         OPTIONS(description="year actual number"),
    first_day_of_month       DATE         OPTIONS(description="first day of the month"),
    last_day_of_month       DATE         OPTIONS(description="last day of the month"),
    first_day_of_quarter       DATE         OPTIONS(description="first day of the quarter"),
    last_day_of_quarter       DATE         OPTIONS(description="last day of the quarter"),
    first_day_of_year       DATE         OPTIONS(description="first day of the year"),
    last_day_of_year       DATE         OPTIONS(description="last day of the year"),
    yyyymm       STRING         OPTIONS(description="yyyymm"),
    weekend_indr       BOOLEAN         OPTIONS(description="weekend indicaton"),
);
